### ISSUE TITLE
Can't auto create a folder of remote is remote  folder is not existing

### ISSUE THREAD

**Issue by mickey9910326** [mickey9910326/ftpbackup#1]
If remote is 'dir/tardir',  and tardir is not existing. Will get this error.
```
Traceback (most recent call last):
  File "D:\Programs\Python\Python36-32\Scripts\ftpbk-script.py", line 11, in <module>
    load_entry_point('ftpbackup==0.1.5', 'console_scripts', 'ftpbk')()
  File "d:\programs\python\python36-32\lib\site-packages\ftpbackup\__main__.py", line 91, in run
    args.func(args)
  File "d:\programs\python\python36-32\lib\site-packages\ftpbackup\__main__.py", line 40, in subBackup
    ftpBackup.startBackup()
  File "d:\programs\python\python36-32\lib\site-packages\ftpbackup\__init__.py", line 168, in startBackup
    self._ftp.cwd(remotedir)
  File "d:\programs\python\python36-32\lib\ftplib.py", line 631, in cwd
    return self.voidcmd(cmd)
  File "d:\programs\python\python36-32\lib\ftplib.py", line 278, in voidcmd
    return self.voidresp()
  File "d:\programs\python\python36-32\lib\ftplib.py", line 251, in voidresp
    resp = self.getresp()
  File "d:\programs\python\python36-32\lib\ftplib.py", line 246, in getresp
    raise error_perm(resp)
ftplib.error_perm: 550 /123: No such file or directory
```

**Comment by mickey9910326** [comment]
solved in 0.1.6
